# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterInstant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirstProject-Objc
  pod 'ReactiveCocoa', '~> 2.5'
  pod 'LinqToObjectiveC', '2.0.0'

end
